var input1 = [
    {name: 'x', x: 1, y: 1, z: 1},
    {name: 'y', x: 1, y: 1, z: 1},
    {name: 'z', x: 1, y: 1, z: 1},
    {name: 'x', x: 1, y: 1},
    {name: 'x', x: 1, y: 1},
    {name: 'x', x: 1, y: 1},
    {name: 'x', x: 1, z: 1},
    {name: 'x', x: 1, z: 1},
    {name: 'x', x: 1, z: 1},
    {name: 'x', y: 1, z: 1},
    {name: 'y', y: 1, z: 1},
    {name: 'z', y: 1, z: 1},
    {name: 'z'},
    {name: 'z'},
    {name: 'z'},
    {name: 'z'},
    {name: 'z'},
    {name: 'z'},
    {name: 'z'},
    {name: 'z'},
    {name: 'z'},
    {name: 'z'},
    {name: 'z'},
    {name: 'z'},
    {name: 'z'},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 2, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: false},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 2, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: false},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 2, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: false},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 2, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: false},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 2, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: false},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 2, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: false},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 2, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: false},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 2, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: false},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 2, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 4, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 2, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: false},
    {name: 'xx', x: 1, y: 1, z: 2, blabla: true},
    {name: 'x', x: 1, y: 1, z: 1},
    {name: 'y', x: 1, y: 1, z: 1},
    {name: 'z', x: 1, y: 1, z: 1},
    {name: 'xx', x: 1, y: 1, z: 1, blabla: true}
];
