{var XJSTParser=exports.XJSTParser=objectThatDelegatesTo(BSJSParser,{
"const":function(){var $elf=this,_fromIdx=this.input.idx,s,n;return this._or((function(){return this._form((function(){return (function(){this._applyWithArgs("exactly","string");return s=this._apply("anything")}).call(this)}))}),(function(){return this._form((function(){return (function(){this._applyWithArgs("exactly","number");return n=this._apply("anything")}).call(this)}))}))},
"isKeyword":function(){var $elf=this,_fromIdx=this.input.idx,x;return (function(){x=this._apply("anything");return this._pred(((BSJSParser._isKeyword(x) || (x === "local")) || (x === "template")))}).call(this)},
"stmt":function(){var $elf=this,_fromIdx=this.input.idx,c,t;return this._or((function(){return (function(){this._applyWithArgs("token","local");this._applyWithArgs("token","(");c=this._apply("expr");this._applyWithArgs("token",")");t=this._apply("stmt");return XJSTParser.match(["local",c,t],"local")}).call(this)}),(function(){return BSJSParser._superApplyWithArgs(this,'stmt')}))},
"local":function(){var $elf=this,_fromIdx=this.input.idx,es,t;return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","local");es=this._apply("localExprs");return t=this._apply("anything")}).call(this)}));return (function (){var id = XJSTParser._getLocalId(),res = ["begin"];es.forEach((function (x){res["push"].apply(res,x[(0)])}));res.push(t);es.reverse().forEach((function (x){res["push"].apply(res,x[(1)])}));return res}).call(this)}).call(this)},
"localExprs":function(){var $elf=this,_fromIdx=this.input.idx,e1,es,e2;return this._or((function(){return (function(){e1=this._apply("localExpr");return [e1]}).call(this)}),(function(){return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","binop");this._applyWithArgs("exactly",",");es=this._apply("localExprs");return e2=this._apply("localExpr")}).call(this)}));return (function (){es.push(e2);return es}).call(this)}).call(this)}))},
"localExpr":function(){var $elf=this,_fromIdx=this.input.idx,n,p,v,k,o,p,v,k,o,p,v;return this._or((function(){return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","set");p=this._form((function(){return (function(){this._applyWithArgs("exactly","get");return n=this._apply("anything")}).call(this)}));return v=this._apply("anything")}).call(this)}));return (function (){var id = XJSTParser._getLocalId();return [[["var",[("__v" + id),p]],["set",["get",n],v]],[["set",["get",n],["get",("__v" + id)]]]]}).call(this)}).call(this)}),(function(){return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","set");p=this._form((function(){return (function(){this._applyWithArgs("exactly","getp");k=this._apply("const");return o=this._apply("anything")}).call(this)}));return v=this._apply("anything")}).call(this)}));return (function (){var id = XJSTParser._getLocalId(),vTree = ["getp",k,["get",("__o" + id)]];return [[["var",[("__o" + id),o],[("__v" + id),vTree]],["set",vTree,v]],[["set",vTree,["get",("__v" + id)]]]]}).call(this)}).call(this)}),(function(){return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","set");p=this._form((function(){return (function(){this._applyWithArgs("exactly","getp");k=this._apply("anything");return o=this._apply("anything")}).call(this)}));return v=this._apply("anything")}).call(this)}));return (function (){var id = XJSTParser._getLocalId(),vTree = ["getp",["get",("__k" + id)],["get",("__o" + id)]];return [[["var",[("__o" + id),o],[("__k" + id),k],[("__v" + id),vTree]],["set",vTree,v]],[["set",vTree,["get",("__v" + id)]]]]}).call(this)}).call(this)}))},
"subMatch":function(){var $elf=this,_fromIdx=this.input.idx,e1,c,c,e2,e3;return this._or((function(){return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","binop");this._applyWithArgs("exactly","===");e1=this._apply("anything");return c=this._apply("const")}).call(this)}));return [e1,c]}).call(this)}),(function(){return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","binop");this._applyWithArgs("exactly","===");c=this._apply("const");return e2=this._apply("anything")}).call(this)}));return [e2,c]}).call(this)}),(function(){return (function(){e3=this._apply("anything");return [["unop","!",e3],["get","false"]]}).call(this)}))},
"expr2match":function(){var $elf=this,_fromIdx=this.input.idx,ms,m1,m2;return this._or((function(){return (function(){this._form((function(){return (function(){this._applyWithArgs("exactly","binop");this._applyWithArgs("exactly","&&");ms=this._apply("expr2match");return m1=this._apply("subMatch")}).call(this)}));return (function (){ms.push(m1);return ms}).call(this)}).call(this)}),(function(){return (function(){m2=this._apply("subMatch");return [m2]}).call(this)}))},
"template":function(){var $elf=this,_fromIdx=this.input.idx,m,b;return (function(){this._applyWithArgs("token","template");this._applyWithArgs("token","(");m=this._apply("expr");this._applyWithArgs("token",")");b=this._apply("stmt");return [XJSTParser.match(m,"expr2match"),b]}).call(this)},
"topLevel":function(){var $elf=this,_fromIdx=this.input.idx,t,s,ts;return (function(){ts=this._many1((function(){return this._or((function(){return (function(){t=this._apply("template");return ["template",t]}).call(this)}),(function(){return (function(){s=this._apply("srcElem");return ["stmt",s]}).call(this)}))}));this._apply("spaces");this._apply("end");return XJSTParser._splitTemplates(ts)}).call(this)}});(XJSTParser["_getLocalIdCounter"]=(0));(XJSTParser["_getLocalId"]=(function (){return this["_getLocalIdCounter"]++}));(XJSTParser["_splitTemplates"]=(function (ts){var templates = [],other = [],i = undefined;while((i=ts.shift())){((i[(0)] == "template")?templates.unshift(i[(1)]):other.push(i[(1)]))};return [other,XJSTParser._identify(templates)]}));(XJSTParser["_identify"]=(function (templates){var predicates = new Identifier();templates.forEach((function (template){template[(0)].forEach((function (subMatch){subMatch.unshift(predicates.identify(subMatch[(0)]))}))}));return templates}));var XJSTCompiler=exports.XJSTCompiler=objectThatDelegatesTo(BSJSTranslator,{
"subMatch":function(){var $elf=this,_fromIdx=this.input.idx,id,m,id,e,c;return this._or((function(){return (function(){this._form((function(){return (function(){id=this._apply("anything");m=this._apply("trans");return this._form((function(){return (function(){this._applyWithArgs("exactly","get");return this._applyWithArgs("exactly","true")}).call(this)}))}).call(this)}));return m}).call(this)}),(function(){return (function(){this._form((function(){return (function(){id=this._apply("anything");e=this._apply("trans");return c=this._apply("trans")}).call(this)}));return ((e + " === ") + c)}).call(this)}))},
"tMatch":function(){var $elf=this,_fromIdx=this.input.idx,m,ms;return this._or((function(){return (function(){this._form((function(){return m=this._apply("subMatch")}));return m}).call(this)}),(function(){return (function(){this._form((function(){return ms=this._many1((function(){return this._apply("subMatch")}))}));return ms.join(" && ")}).call(this)}))},
"tBody":function(){var $elf=this,_fromIdx=this.input.idx,e;return (function(){e=this._apply("trans");return e}).call(this)},
"template":function(){var $elf=this,_fromIdx=this.input.idx,m,b;return (function(){this._form((function(){return (function(){m=this._apply("tMatch");return b=this._apply("tBody")}).call(this)}));return (((("    if(" + m) + ") {") + b) + ";return}")}).call(this)},
"templates":function(){var $elf=this,_fromIdx=this.input.idx,ts;return (function(){this._form((function(){return ts=this._many((function(){return this._apply("template")}))}));return (("exports.apply = function(c){\n" + ts.join("\n")) + "\n};")}).call(this)},
"other":function(){var $elf=this,_fromIdx=this.input.idx,o;return (function(){this._form((function(){return o=this._many((function(){return this._apply("trans")}))}));return o.join(";")}).call(this)},
"topLevel":function(){var $elf=this,_fromIdx=this.input.idx,o,t;return (function(){this._form((function(){return (function(){o=this._apply("other");return t=this._apply("templates")}).call(this)}));return (((("(function(exports){" + o) + ";") + t) + "return exports})(typeof exports === \"undefined\"? {} : exports)")}).call(this)}})}
